
export const schemeFilterTable = () => [
  {
    label: "Order Id",
    type: "Input",
    field: "transactionCode",
    value: "",
    width: "25%",
  },
  {
    label: "Promo Code",
    type: "Input",
    field: "promoCode",
    value: "",
    width: "25%",
  },
  {
    label: "Ticket Status",
    type: "Select",
    field: "ticketStatus",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "BOOKED", label: "BOOKED" },
      { value: "COMPLETED", label: "COMPLETED" },
      { value: "CANCELLED", label: "CANCELLED" },
      { value: "EXPIRED", label: "EXPIRED" },
      { value: "TICKETED", label: "TICKETED" },
      { value: "PAID", label: "PAID" },
      { value: "REFUNDED", label: "REFUNDED" },
      { value: "NEED REVIEW", label: "NEED REVIEW" },
      { value: "UNPAID", label: "UNPAID" },
    ],
    width: "25%",
  }, 
  {
    label: "Tour Name",
    type: "Input",
    field: "tourName",
    value: "",
    width: "25%",
  },
  {
    label: "Promo Type",
    type: "Select",
    field: "promoType",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "promo", label: "Promo" },
      { value: "non-promo", label: "Non Promo" },
    ],
    width: "25%",
  },
  {
    label: "Start Date (Booking Date)",
    type: "Date",
    field: "bookingDateStart",
    value: "",
    width: "25%",
  },
  {
    label: "End Date (Booking Date)",
    type: "Date",
    field: "bookingDateEnd",
    value: "",
    width: "25%",
  },
  {
    label: "Departure Date",
    type: "Date",
    field: "tourDepartureDate",
    value: "",
    width: "25%",
  },
  {
    label: "Order Status",
    type: "Select",
    field: "orderStatus",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "booked", label: "BOOKED" },
      { value: "unpaid", label: "UNPAID" },
      { value: "expired", label: "EXPIRED" },
      { value: "paid", label: "PAID" },
      { value: "cancelled", label: "CANCELLED" },
      { value: "completed", label: "COMPLETED" }
      // { value: "booked", label: "Transaksi dipesan" },
      // { value: "unpaid", label: "Transaksi menunggu pembayaran" },
      // { value: "expired", label: "Transaksi lewat jatuh tempo" },
      // { value: "paid", label: "Transaksi berhasil terbayar" },
      // { value: "cancelled", label: "Transaksi dibatalkan" },
      // { value: "completed", label: "Transaksi selesai" }
    ],
    width: "25%",
  },   
  {
    label: "Payment Method",
    type: "Select",
    field: "paymentMethod",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "allopoint", label: "Allo Point" },
      { value: "allopay", label: "Allo Pay" },
      { value: "allopaylater", label: "Allo Paylater" },
      { value: "briva", label: "Bank BRI VA" },
      { value: "bniva", label: "Bank BNI VA" },
      { value: "bankmega", label: "Bank Mega" },
      { value: "megacc", label: "Bank Mega CC" },
      { value: "megadc", label: "Bang Mega DC" },
      { value: "megava", label: "Bank Mega VA" },
      { value: "mandiriva", label: "Mandiri VA" },
    ],
    width: "25%",
  },
  {
    label: "Platform",
    type: "Select",
    field: "platform",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "web", label: "Website" },
      { value: "ios", label: "iOS" },
      { value: "android", label: "Android" },
    ],
    width: "25%",
  },
  {
    label: "Apply Filter",
    type: "ButtonAction",
    disabled: false,
    width: "110px",
    style: "ant-btn gx-btn-secondary ",
  },
  {
    label: "Export Excel",
    type: "ButtonDownload",
    disabled: false,
    width: "110px",
    style: "ant-btn",
  },
];