
export const schemeFilterTable = () => [
  {
    label: "Order Id",
    type: "Input",
    field: "transactionCode",
    value: "",
    width: "25%",
  },
  {
    label: "Booking Code",
    type: "Input",
    field: "bookingCode",
    value: "",
    width: "25%",
  },
  {
    label: "Order Status",
    type: "Select",
    field: "orderStatus",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "booked", label: "BOOKED" },
      { value: "unpaid", label: "UNPAID" },
      { value: "expired", label: "EXPIRED" },
      { value: "paid", label: "PAID" },
      { value: "cancelled", label: "CANCELLED" },
      { value: "completed", label: "COMPLETED" }
      // { value: "booked", label: "Transaksi dipesan" },
      // { value: "unpaid", label: "Transaksi menunggu pembayaran" },
      // { value: "expired", label: "Transaksi lewat jatuh tempo" },
      // { value: "paid", label: "Transaksi berhasil terbayar" },
      // { value: "cancelled", label: "Transaksi dibatalkan" },
      // { value: "completed", label: "Transaksi selesai" }
    ],
    width: "25%",
  },
  {
    label: "Start Date",
    type: "Date",
    field: "bookingDateStart",
    value: "",
    width: "25%",
  },
  {
    label: "Passenger Name",
    type: "Input",
    field: "passangerName",
    value: "",
    width: "25%",
  },
  {
    label: "Origin",
    type: "Input",
    field: "originCity",
    value: "",
    width: "25%",
  },
  {
    label: "Ticket Status",
    type: "Select",
    field: "ticketStatus",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "BOOKED", label: "BOOKED" },
      { value: "COMPLETED", label: "COMPLETED" },
      { value: "CANCELLED", label: "CANCELLED" },
      { value: "EXPIRED", label: "EXPIRED" },
      { value: "TICKETED", label: "TICKETED" },
      { value: "PAID", label: "PAID" },
      { value: "REFUNDED", label: "REFUNDED" },
      { value: "NEED REVIEW", label: "NEED REVIEW" },
      { value: "UNPAID", label: "UNPAID" },
    ],
    width: "25%",
  },
  {
    label: "End Date",
    type: "Date",
    field: "bookingDateEnd",
    value: "",
    width: "25%",
  },
  {
    label: "Cust. Email",
    type: "Input",
    field: "customerEmail",
    value: "",
    width: "25%",
  },
  {
    label: "Destination",
    type: "Input",
    field: "destinationCity",
    value: "",
    width: "25%",
  },
  {
    label: "Payment Method",
    type: "Select",
    field: "paymentMethod",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "allopoint", label: "Allo Point" },
      { value: "allopay", label: "Allo Pay" },
      { value: "allopaylater", label: "Allo Paylater" },
      { value: "briva", label: "Bank BRI VA" },
      { value: "bniva", label: "Bank BNI VA" },
      { value: "bankmega", label: "Bank Mega" },
      { value: "megacc", label: "Bank Mega CC" },
      { value: "megadc", label: "Bang Mega DC" },
      { value: "megava", label: "Bank Mega VA" },
      { value: "mandiriva", label: "Mandiri VA" },
    ],
    width: "25%",
  },
  {
    label: "Start Date (Flight)",
    type: "Date",
    field: "departureDateStart",
    value: "",
    width: "25%",
  },
  {
    label: "Customer Phone",
    type: "Input",
    field: "customerPhoneNumber",
    value: "",
    width: "25%",
  },
  {
    label: "Flight Number",
    type: "Input",
    field: "flightNumber",
    value: "",
    width: "25%",
  },
  {
    label: "Payment Date",
    type: "Date",
    field: "paymentDate",
    value: "",
    width: "25%",
  },
  {
    label: "End Date (Flight)",
    type: "Date",
    field: "departureDateEnd",
    value: "",
    width: "25%",
  },
  {
    label: "Airline",
    type: "Input",
    field: "airlineName",
    value: "",
    width: "25%",
  },
  {
    label: "Route",
    type: "Select",
    field: "routeType",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "domestic", label: "Domestic" },
      { value: "international", label: "International" },
    ],
    width: "25%",
  }, 
  {
    label: "Expired Date",
    type: "Date",
    field: "bookingExpiredDate",
    value: "",
    width: "25%",
  },
  {
    label: "Price",
    type: "Input",
    field: "price",
    value: "",
    width: "25%",
  },
  {
    label: "Platform",
    type: "Select",
    field: "platform",
    value: "",
    options: [
      { value: "", label: "All" },
      { value: "web", label: "Website" },
      { value: "ios", label: "iOS" },
      { value: "android", label: "Android" },
      { value: "web - Sukha", label: "Website - Sukha" },
    ],
    width: "25%",
  },
  {
    label: "Apply Filter",
    type: "ButtonAction",
    disabled: false,
    width: "110px",
    style: "ant-btn",
  },
  {
    label: "Export Excel",
    type: "ButtonDownload",
    disabled: false,
    width: "110px",
    style: "ant-btn",
  },
];