export const schemaModal = ()=>{
  return {
    productType:{
      value: "",
      type: "Select",
      label:"Product Type",
      options:[
        { value:"",label:"Please Select"},
        { value: "All", label: "All" },
        { value: "flight", label: "Flight" },
        { value: "hotel", label: "Hotel" },
        { value: "tour", label: "Tour" },
      ],
      required: true,
      error: "",
    },
    type:{
      value: "",
      type: "Select",
      label:"Promo Type",
      options:[
        { value:"",label:"Please Select"},
        { value: "amount", label: "Amount" },
        { value: "percentage", label: "Percentage" },
      ],
      required: true,
      error: "",
    },
    platform:{
      value: "",
      type: "Select",
      label:"Platform",
      options:[
        { value:"",label:"Please Select"},
        { value: "All", label: "All" },
        { value: "Web", label: "Web" },
        { value: "App", label: "App" },
      ],
      required: true,
      error: "",
    },
    tourCode:{
      value: "",
      type: "Select",
      label:"Tour Name",
      required: true,
      error: "",
    },
    regionName:{
      value: "",
      type: "Select",
      label:"Region Name",
      required: true,
      error: "",
    },
    airlineCode:{
      value: "",
      type: "Select",
      label:"Airline Name",
      required: true,
      error: "",
    },
    originCode:{
      value: "",
      type: "Select",
      label:"Origin Name",
      required: true,
      error: "",
    },
    destinationCode:{
      value: "",
      type: "Select",
      label:"Destination Name",
      required: true,
      error: "",
    },
    hotelCode:{
      value: "",
      type: "Select",
      label:"Hotel Name",
      required: true,
      error: "",
    },
    promoCode:{
      value: "",
      type: "Input",
      label:"Promo Code",
      validationType:"alphanumeric",
      required: true,
      error: "",
    },
    promoName:{
      value: "",
      type: "Input",
      label:"Promo Name",
      required: true,
      validationType:"alphanumeric",
      error: "",
    },
    promoDescription:{
      value: "",
      type: "InputArea",
      label:"Promo Description",
      required: true,
      error: "",
    },
    tnc:{
      value: "",
      type: "InputArea",
      label:"Tnc",
      required: true,
      error: "",
    },
    desktopImageUrl:{
      value: "",
      type: "Upload",
      label: "Desktop Image",
      required: true,
      error: "",
      dimension: { width: 1280, height: 500, validate: false }
    },
    mobileImageUrl:{
      value: "",
      type: "Upload",
      label: "Mobile Image",
      required: true,
      error: "",
      dimension: { width: 640, height: 250, validate: false }
    },
    startDate:{
      value: "",
      type: "Date",
      label:"Start Date",
      format: "DD-MM-YYYY HH:mm",
      showTime: { format: 'HH:mm' },
      required: true,
      error: "",
    },
    endDate:{
      value: "",
      type: "Date",
      label:"End Date",
      format: "DD-MM-YYYY HH:mm",
      showTime: { format: 'HH:mm' },
      required: true,
      error: "",
    },
    quota:{
      value: "",
      validationType:"numeric",
      type: "Input",
      label:"Quota",
      required: true,
      error: "",
    },
    minimumTransaction:{
      value: "",
      validationType:"numeric",
      type: "Input",
      label:"Minimum Transaction",
      required: true,
      error: "",
    },
    percentageDiscount:{
      value: "",
      validationType:"numeric",
      type: "hidden",
      label:"Percentage Discount",
      required: true,
      error: "",
    },
    maximumDiscount:{
      value: "",
      validationType:"numeric",
      type: "hidden",
      label:"Maximum Discount",
      required: true,
      error: "",
    },
    amount:{
      value: "",
      validationType:"numeric",
      type: "hidden",
      label:"Amount",
      required: true,
      error: "",
    },
    isOncePerUser:{
      value: true,
      validationType:"boolean",
      type: "Switch",
      label:"Is Per User",
      error: "",
    },
    isForEmployee:{
      value: true,
      validationType:"boolean",
      type: "Switch",
      label:"Is For Employee",
      error: "",
    },
    isHidden:{
      value: true,
      validationType:"boolean",
      type: "Switch",
      label:"Is Hidden",
      error: "",
    }
  }
}